### ISSUE TITLE
About Fmod

### ISSUE THREAD

**Issue by MorningDemon515** [blitz-research/blitz3d_msvc2017#10]
Hi! mark

I'm curious, which version of fmod was used before blitz3d1.108

**Comment by blitz-research** [comment]
Hi, sorry about the delay!

Regarding FMOD, I don't quite remember what version Blitz3D used to use, but I think it was more or less the same as the version in the repos.

I do remember the FMOD API changed significantly shortly afterwards, so the version in the repos is likely to be the 'most recent' of it's kind, or near to it.
