### ISSUE TITLE
fmod.dll needed to use exe

### ISSUE THREAD

**Issue by Raf20076** [blitz-research/blitz3d_msvc2017#15]
Unfortunately fmod.dll is needed to use .exe. Fmod is not open source and it's commercial. Any chance for open source implementation sound managment? With all respect for your work, what is the point to use open source software which needs commercial component?

**Comment by blitz-research** [comment]
I obtained permission from the author of FMOD to include the fmod3 with Blitz3D back when I first released it as open source. In fact, he tracked down the static lib component need to build it.
