### ISSUE TITLE
BlitzIDE skips a line when you press ENTER

### ISSUE THREAD

**Issue by Chaduke** [blitz-research/blitz3d_msvc2017#2]
Is this the default behavior?  Just compiled it today with the latest VS 2017.  
For instance if you're on line 2 and you press ENTER you'll jump down to line 4, then 6, etc.

**Comment by davecamp** [comment]
In the 'blitzide' project, 'editor.cpp' file remove lines 647 to 656 to fix this issue.

**Comment by blitz-research** [comment]
https://github.com/blitz-research/blitz3d_msvc2017/commit/b34bc92ddf17f065da79907d95f61622dc09581b
