### ISSUE TITLE
LoadSprite and LoadImage both crash to desktop in Windows 10.

### ISSUE THREAD

**Issue by Sarah-C** [blitz-research/blitz3d_msvc2017#3]
samples\AGore\GrassDemo\Grass.bb

When compiled and run with no changes it crashes to desktop when running this line: tex1=LoadTexture( "Data\GrassClip.bmp",10 )

The Windows event log shows a low level app crash, without any nice programmers error messages.

It also crashes on LoadSprite too!

**Comment by blitz-research** [comment]
Fixed here: https://github.com/blitz-research/blitz3d_msvc2017/commit/a3bd34ce758268ecdb07ab431fc618731984138e
